---
- name: sample book
  hosts: ansible_client
  remote_user: root
  become: true
  tasks:
    - name: install apache2
      apt:
          name: apache2
          state: latest
    - name: run apache
      service:
              name: apache2
              state: started
    - name: create content 
      copy:
           content: "Hello ansible" 
           dest: /var/www/html/index.html
